# Generated by Django 5.0.1 on 2024-03-04 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySQL_CRUD', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerform',
            name='contact',
            field=models.IntegerField(),
        ),
    ]
